name: compile-project
run-name: Compile project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          # Make sure to set a version number!
          version: 1.38.40
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'

      - name: Build
        run: |
          mkdir out
          emcc test.cpp -o out/test.html
        
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: out
